name: bayes_chl
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - scikit-learn=0.21.3
  - numpy=1.17.3
  - pandas=0.25.0
  - pymc3=3.7
  - arviz=0.5.1
  - mkl-service
  - python-graphviz=0.10.1
  - pyarrow=0.15.1
  - jupyter_contrib_nbextensions=0.5.1
